service: erp-crm

frameworkVersion: '3'

provider:
  stage: prod
  name: aws
  runtime: nodejs18.x  
  memorySize: 3008
  region: ap-south-1
  



functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

  