service: erp-crm

frameworkVersion: '3'

provider:
  stage: prod
  name: aws
  runtime: nodejs18.x  
  memorySize: 3008
  region: ap-south-1
  



functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

  websocketConnect:
    handler: server.handler
    events:
      - websocket:
          route: $connect

  websocketDisconnect:
    handler: server.handler
    events:
      - websocket:
          route: $disconnect

  websocketDefault:
    handler: server.handler
    events:
      - websocket:
          route: $default

  websocketSetName:
    handler: server.handler
    events:
      - websocket:
          route: setName

  websocketSendPublic:
    handler: server.handler
    events:
      - websocket:
          route: sendPublic

  websocketSendPrivate:
    handler: server.handler
    events:
      - websocket:
          route: sendPrivate
